import { run } from './solana-test-validator'
import { MarinadeConfig } from '../../src/config/marinade-config'

const config = new MarinadeConfig()

run([
  {
    address: config.marinadeFinanceProgramId,
    path: 'resources/tests/programs/marinade_finance.so',
  },
  {
    address: config.marinadeReferralProgramId,
    path: 'resources/tests/programs/marinade_referral.so',
  },
],
{directory: './resources/tests/solana-accounts/'},
// [
//   { address: new web3.PublicKey('8ZDy8KZKM7sbPJuXBY6DdX4sWevTmu1tE1RbrycXm1Xr'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/8ZDy8KZKM7sbPJuXBY6DdX4sWevTmu1tE1RbrycXm1Xr.json' },
//   { address: new web3.PublicKey('4B7PSNmfTC1wUhn4mdDM5E7DtDbNV1mktLbiebeK6QqG'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/4B7PSNmfTC1wUhn4mdDM5E7DtDbNV1mktLbiebeK6QqG.json' },
//   { address: new web3.PublicKey('4k7kR5hLC7mbe4J5kfJRuEfpyxojFs1enUjMe71wodVn'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/4k7kR5hLC7mbe4J5kfJRuEfpyxojFs1enUjMe71wodVn.json' },
//   { address: new web3.PublicKey('7Zuu7HfxGSqtuDeWHb48hHUgDtyeTL7YyoUQL2F3Tzfb'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/7Zuu7HfxGSqtuDeWHb48hHUgDtyeTL7YyoUQL2F3Tzfb.json' },
//   { address: new web3.PublicKey('5gKGWkrC3fSodG7uSba1thnPBGSfBVsk54SfRN2Ad7KE'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/5gKGWkrC3fSodG7uSba1thnPBGSfBVsk54SfRN2Ad7KE.json' },
//   { address: new web3.PublicKey('2rKtsfwC1cG3yHHzWj3bKynWvidhgDLkck6ayWgDovsz'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/2rKtsfwC1cG3yHHzWj3bKynWvidhgDLkck6ayWgDovsz.json' },
//   { address: new web3.PublicKey('CXR8V6CTb4wsNt5pGa2jGB95v2QUYBPAcWzDALG7AZDV'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/CXR8V6CTb4wsNt5pGa2jGB95v2QUYBPAcWzDALG7AZDV.json' },
//   { address: new web3.PublicKey('EvCd2BG8umDhYbJobsBDXrVgsP6KqTGbzA3kwicZzFhF'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/EvCd2BG8umDhYbJobsBDXrVgsP6KqTGbzA3kwicZzFhF.json' },
//   { address: new web3.PublicKey('DwQ6N4YVac7wbPqnUMpDUiWqTDu2YesYbHMHbfRsPacm'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/DwQ6N4YVac7wbPqnUMpDUiWqTDu2YesYbHMHbfRsPacm.json' },
//   { address: new web3.PublicKey('2jQQEUjVgxiW7M4d34ABTRFHJxwR3bJtM2KUHqmYj4Cb'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/2jQQEUjVgxiW7M4d34ABTRFHJxwR3bJtM2KUHqmYj4Cb.json' },
//   { address: new web3.PublicKey('DNfb2G1EpXtpXCTZkhLexh1MS3J8ub8G5TDUcde85JKB'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/DNfb2G1EpXtpXCTZkhLexh1MS3J8ub8G5TDUcde85JKB.json' },
//   { address: new web3.PublicKey('FjHzxBGLzDstYt5ghbtyBGcThBiC3GU44F21cDdoKuqD'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/FjHzxBGLzDstYt5ghbtyBGcThBiC3GU44F21cDdoKuqD.json' },
//   { address: new web3.PublicKey('7EvaQwc6vwzVaZ9pA8GcCrWYJp8SivZjsHn9nrc7NRjt'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/7EvaQwc6vwzVaZ9pA8GcCrWYJp8SivZjsHn9nrc7NRjt.json' },
//   { address: new web3.PublicKey('36rnk8SPmprGtFG7UFZvTBeCREMQ3JCsDqmb1KFsKHYN'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/36rnk8SPmprGtFG7UFZvTBeCREMQ3JCsDqmb1KFsKHYN.json' },
//   { address: new web3.PublicKey('4Amq9DYbHvg3Yofvoz2KJeZye84CZGZnNye1QnBpyekW'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/4Amq9DYbHvg3Yofvoz2KJeZye84CZGZnNye1QnBpyekW.json' },
//   { address: new web3.PublicKey('5KVZ7m2AFDPpGXgUDSYomad2iSJeMhGkqn5j8LTD86m8'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/5KVZ7m2AFDPpGXgUDSYomad2iSJeMhGkqn5j8LTD86m8.json' },
//   { address: new web3.PublicKey('GFthjVWZk3reXE1YJexPzMzER4fGyFtcwgAMJSiK9t59'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/GFthjVWZk3reXE1YJexPzMzER4fGyFtcwgAMJSiK9t59.json' },
//   { address: new web3.PublicKey('4a3MBEQubAC9XDSy22MrKtt3dJae2LMeS9crPpR4Eai6'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/4a3MBEQubAC9XDSy22MrKtt3dJae2LMeS9crPpR4Eai6.json' },
//   { address: new web3.PublicKey('3oEiYNpgXiFUAiDrcw4iVt2c4q6Yv8rP2DxSiRihwW7x'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/3oEiYNpgXiFUAiDrcw4iVt2c4q6Yv8rP2DxSiRihwW7x.json' },
//   { address: new web3.PublicKey('DAX8sbk4H8Wr8gvfGCEExx2oBnk3N2Y72CSXpZMcPFDv'), path: './resources/tests/solana-accounts/marinade_finance/marinade-validator-duplication-flag/DAX8sbk4H8Wr8gvfGCEExx2oBnk3N2Y72CSXpZMcPFDv.json' },
//   { address: new web3.PublicKey('CUuLjSEx7q3AB3sRGn3sMJBsSNTmULwowMGUh6NdsxQD'), path: './resources/tests/solana-accounts/marinade_finance/CUuLjSEx7q3AB3sRGn3sMJBsSNTmULwowMGUh6NdsxQD.json' },
//   { address: new web3.PublicKey('8szGkuLTAux9XMgZ2vtY39jVSowEcpBfFfD8hXSEqdGC'), path: './resources/tests/solana-accounts/marinade_finance/8szGkuLTAux9XMgZ2vtY39jVSowEcpBfFfD8hXSEqdGC.json' },
//   { address: new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'), path: './resources/tests/solana-accounts/marinade_finance/MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD.json' },
//   { address: new web3.PublicKey('mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So'), path: './resources/tests/solana-accounts/marinade_finance/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So.json' },
//   { address: new web3.PublicKey('LPmSozJJ8Jh69ut2WP3XmVohTjL4ipR18yiCzxrUmVj'), path: './resources/tests/solana-accounts/marinade_finance/LPmSozJJ8Jh69ut2WP3XmVohTjL4ipR18yiCzxrUmVj.json' },
//   { address: new web3.PublicKey('8qfSJCVHGehG3LSteUGWcog9S4csU9F3oCKnceF5FKDH'), path: './resources/tests/solana-accounts/marinade_finance/8qfSJCVHGehG3LSteUGWcog9S4csU9F3oCKnceF5FKDH.json' },
//   { address: new web3.PublicKey('Du3Ysj1wKbxPKkuPPnvzQLQh8oMSVifs3jGZjJWXFmHN'), path: './resources/tests/solana-accounts/marinade_finance/Du3Ysj1wKbxPKkuPPnvzQLQh8oMSVifs3jGZjJWXFmHN.json' },
//   { address: new web3.PublicKey('7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE'), path: './resources/tests/solana-accounts/marinade_finance/7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE.json' },
//   { address: new web3.PublicKey('UefNb6z6yvArqe4cJHTXCqStRsKmWhGxnZzuHbikP5Q'), path: './resources/tests/solana-accounts/marinade_finance/UefNb6z6yvArqe4cJHTXCqStRsKmWhGxnZzuHbikP5Q.json' },
//   { address: new web3.PublicKey('Anv3XE7e5saNdm16MU6bniYS59Mpv7DzQXHAhxJUmAKW'), path: './resources/tests/solana-accounts/marinade_finance/Anv3XE7e5saNdm16MU6bniYS59Mpv7DzQXHAhxJUmAKW.json' },
//   { address: new web3.PublicKey('DwFYJNnhLmw19FBTrVaLWZ8SZJpxdPoSYVSJaio9tjbY'), path: './resources/tests/solana-accounts/marinade_finance/DwFYJNnhLmw19FBTrVaLWZ8SZJpxdPoSYVSJaio9tjbY.json' },
//   { address: new web3.PublicKey('HBc7aVtqxYVWhq7rPdGzTee15kYfeK1WvYZidBuA44TZ'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/HBc7aVtqxYVWhq7rPdGzTee15kYfeK1WvYZidBuA44TZ.json' },
//   { address: new web3.PublicKey('3e1mBFJwuuZU6iTYaHhrFbSdo1A6BjzhLLqQXmYZmCUh'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/3e1mBFJwuuZU6iTYaHhrFbSdo1A6BjzhLLqQXmYZmCUh.json' },
//   { address: new web3.PublicKey('3pC73wDekDrRDpbeWmxZdct9WfMLaP4WR1wjzgJL5dXU'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/3pC73wDekDrRDpbeWmxZdct9WfMLaP4WR1wjzgJL5dXU.json' },
//   { address: new web3.PublicKey('4cBWskqFZmdCuVgf3vo3QzPrybx6xqcTkobR5zYvTtvM'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/4cBWskqFZmdCuVgf3vo3QzPrybx6xqcTkobR5zYvTtvM.json' },
//   { address: new web3.PublicKey('6m7yka96mMbcGav7XQgTzZnxtqThgvpCFS2YgqwauGjn'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/6m7yka96mMbcGav7XQgTzZnxtqThgvpCFS2YgqwauGjn.json' },
//   { address: new web3.PublicKey('GdtTBejBWYfbFVh1EUW8JsbNzMn8nsbP5Cg7iPecz117'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/GdtTBejBWYfbFVh1EUW8JsbNzMn8nsbP5Cg7iPecz117.json' },
//   { address: new web3.PublicKey('8axQF64omX8zfPZWhqr7xY1DsuvrB9HX7NuwEBnjwMVS'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/8axQF64omX8zfPZWhqr7xY1DsuvrB9HX7NuwEBnjwMVS.json' },
//   { address: new web3.PublicKey('FppBxJpoyjiVnzFcyR7StFet58DECfCPurVZkzYVxhtr'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/FppBxJpoyjiVnzFcyR7StFet58DECfCPurVZkzYVxhtr.json' },
//   { address: new web3.PublicKey('FMLWHjRqqbvUTTwVYbcJiriXaMaXXGkm5z6CKCUXFn2F'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/FMLWHjRqqbvUTTwVYbcJiriXaMaXXGkm5z6CKCUXFn2F.json' },
//   { address: new web3.PublicKey('H5UgokGRyYKKcYhsHAaskPyti1P1vSiCD31SFhpTgD3U'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/H5UgokGRyYKKcYhsHAaskPyti1P1vSiCD31SFhpTgD3U.json' },
//   { address: new web3.PublicKey('3meVhQj8T4zoVggfg8JhH2z2HN78ee6GLpPoRqcN13za'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/3meVhQj8T4zoVggfg8JhH2z2HN78ee6GLpPoRqcN13za.json' },
//   { address: new web3.PublicKey('7JmSqp8XCDWjcVRYmy77cfBLgLgytEzzHveBjHVai4sf'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/7JmSqp8XCDWjcVRYmy77cfBLgLgytEzzHveBjHVai4sf.json' },
//   { address: new web3.PublicKey('5wepKAJNqHDBrcw9bmULBCfZ5aGEhkSMRxir3VvrZV3x'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/5wepKAJNqHDBrcw9bmULBCfZ5aGEhkSMRxir3VvrZV3x.json' },
//   { address: new web3.PublicKey('2YnuNkxgJFUR6rJDGRh3cgc17bjtYUWqCVc6Bc7JRpp4'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/2YnuNkxgJFUR6rJDGRh3cgc17bjtYUWqCVc6Bc7JRpp4.json' },
//   { address: new web3.PublicKey('26FuvLwZvqGNknUoDnvGL4yUE9563KtfHcR42AqxFK6Z'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/26FuvLwZvqGNknUoDnvGL4yUE9563KtfHcR42AqxFK6Z.json' },
//   { address: new web3.PublicKey('8cUtQuHDZWd8sbd4GJodDq77uyW7BGcHpMGjSjZdiatb'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/8cUtQuHDZWd8sbd4GJodDq77uyW7BGcHpMGjSjZdiatb.json' },
//   { address: new web3.PublicKey('GX1S2JhCK9GKLCz4tsMMYmYRjeK99du93YcDHSCqXPoz'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/GX1S2JhCK9GKLCz4tsMMYmYRjeK99du93YcDHSCqXPoz.json' },
//   { address: new web3.PublicKey('FoJjn2haFBKdREAdYwF3tpfMahdKAVNu2YYCEsZZic3V'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/FoJjn2haFBKdREAdYwF3tpfMahdKAVNu2YYCEsZZic3V.json' },
//   { address: new web3.PublicKey('F4WbX675MwR2jDDMgthim3yzTr9ZpfgH24iByQTWuei'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/F4WbX675MwR2jDDMgthim3yzTr9ZpfgH24iByQTWuei.json' },
//   { address: new web3.PublicKey('Dzv153XS1336Qm7x5RKn95KHGJXER3D1tXeCoh2s8tfp'), path: './resources/tests/solana-accounts/marinade_finance/vote-account/Dzv153XS1336Qm7x5RKn95KHGJXER3D1tXeCoh2s8tfp.json' },
//   { address: new web3.PublicKey('MRSh4rUNrpn7mjAq9ENHV4rvwwPKMij113ScZq3twp2'), path: './resources/tests/solana-accounts/marinade_referral/MRSh4rUNrpn7mjAq9ENHV4rvwwPKMij113ScZq3twp2.json' },
//   { address: new web3.PublicKey('BC25qEnHFSe9jkWA1YtSCUxrps9NXR7tKHv43DQkeh94'), path: './resources/tests/solana-accounts/marinade_referral/BC25qEnHFSe9jkWA1YtSCUxrps9NXR7tKHv43DQkeh94.json' },
//   { address: new web3.PublicKey('2Q7u7ndBhSJpTNpDzkjvRyRvuzRLZSovkNRQ5SEUb64g'), path: './resources/tests/solana-accounts/marinade_referral/2Q7u7ndBhSJpTNpDzkjvRyRvuzRLZSovkNRQ5SEUb64g.json' },
//   { address: new web3.PublicKey('9wmxMQ2TFxYh918RzESjiA1dUXbdRAsXBd12JA1vwWQq'), path: './resources/tests/solana-accounts/9wmxMQ2TFxYh918RzESjiA1dUXbdRAsXBd12JA1vwWQq.json' },
// ],
['--ledger', './.test-ledger', '--reset', '--slots-per-epoch', '32'])
