name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: 7
      - name: Install, build and test
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm build
          pnpm test
        env:
          CI: true
