name: Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
        image: public.ecr.aws/n0y9d4d4/marinade.finance/solana-test-validator:latest
        options: --user root
    timeout-minutes: 15

    strategy:
      fail-fast: true
      matrix:
        node-version: [20]

    steps:
      - name: Link AVM, solana .config, check versions
        run: |
          ln -s /root/.avm $HOME/
          mkdir -p $HOME/.config
          ln -s /root/.config/solana $HOME/.config/
          avm use 0.28.0
          anchor --version
          solana --version


      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install libatomic (required by pnpm binary)
        run: apt-get update && apt-get install -y --no-install-recommends libatomic1
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10
      - name: Install, build and run integration tests
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm build
          pnpm test:integration
        env:
          CI: true
