name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
      - name: Install build and pack
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm build
          pnpm pack
        env:
          CI: true
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          artifacts: "*.tgz,./dist/*.min.js"
          token: ${{ secrets.GITHUB_TOKEN }}
