name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10
      - name: Install build and pack
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm build
          pnpm pack
        env:
          CI: true
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          artifacts: "*.tgz,./dist/*.min.js"
          token: ${{ secrets.GITHUB_TOKEN }}
