name: Trivy - Scan
on:
  pull_request:
jobs:
  trivy:
    name: Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Trivy scanner - generate update
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
        with:
          scan-type: fs
          format: table
          scan-ref: .
          hide-progress: false
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo '```terraform'
              cat trivy.txt
              echo '```'
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Trivy scanner - Fail build on Criticial Vulnerabilities
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
        with:
          scan-type: fs
          format: table
          scan-ref: .
          hide-progress: false
          output: trivy.txt
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1
